%Método de Oldenbourg Sartorius
%Calcula la pendiente y el punto de la tangente
%a la respuesta
%Deben tomarse del workspace la salida,
%la entrada y el tiempo
%La señal de salida debe almacenarse en ys
%El tiempo en t
%La señal de entrada en us
ys=y;
us=u;
tm=t(2)-t(1);%Intervalo de muestreo
long=length(t);
tf1=t(long);%valor final de t
i=0;
tp=-tm;
p=1;
while p>0
tp=tp+tm;
i=i+1;
pendi(i)=ys(i+1)-ys(i);
pendi(i+1)=ys(i+3)-ys(i+2);
p=pendi(i+1)-pendi(i);
%disp(p);
end
ti=tp;%Éste es el valor de t donde ocurre el punto de inflexión
disp(['El punto de inflexión ocurre en t= ',num2str(ti)]);
%pause
tc=0:tm:tp;
longtc=length(tc);
yp=ys(longtc);
pend=(ys(longtc)-ys(longtc-1))/tm;
%Determinaremos ahora Tc
Tc1=(ys(long)-yp+pend*ti)/pend;
Tc=Tc1-ti;
%Cálculo de Ta
Ta0=(ys(1)-yp+pend*ti)/pend;
Ta=Tc1-Ta0;
%Creación de la función T2/TA=F(T1/TA)
T1TA=0:0.1:1;
T2TA=[1 0.73 0.57 0.44 0.34 0.25 0.18 0.12 0.07 0.03 0];
f=polyfit(T1TA,T2TA,6);%Se crea un polinomio de grado 6
Tg=[];
for i=0:0.01:1,
Tg= [Tg polyval(f,i)];
end
abc=0:0.01:1;
a=0;
j=0;
t2tag=[];
hf=figure('NumberTitle','off','ToolBar','figure',...
'Name','Identificación por el Método de Olderbour Sartorius');
for i=0:0.01:1,
j=j+1;
t2tag=[t2tag Tc/Ta-i];
97
if (Tc/Ta-i)>Tg(j)
a=1;
end
end
if a==0
plot(abc,t2tag,abc,Tg);
grid;
warndlg('No hay intersección','Advertencia ')
else
h1 = uicontrol('Parent',hf, ...
'Units','points', ...
'BackgroundColor',[0.8 0.8 0.8], ...
'ListboxTop',0, ...
'Position',[ 20.25 63.75 140.5 19.5 ], ...
'String',['El punto de inflexión ocurre en t= ',num2str(ti)], ...
'Style','text', ...
'Tag','StaticText2');
axes('Position',[ 0.06 0.35 0.40 0.57 ])
plot(abc,t2tag,'b',abc,Tg,'r');
grid;
axis([0 1 0 1]);
title('Gráfica de OS')
Tg1r=Tg-t2tag;
Tg1=find(abs(Tg1r)==min(abs(Tg1r)));
T1Ta=Tg(Tg1);
T2Ta=abc(Tg1);
T1=Tg(Tg1)*Ta;
T2=abc(Tg1)*Ta;
h1 = uicontrol('Parent',hf, ...
'Units','points', ...
'BackgroundColor',[0.8 0.8 0.8], ...
'ListboxTop',0, ...
'Position',[ 20.25 53.75 100.5 19.5 ], ...
'String',['T1 = ',num2str(T1)], ...
'Style','text', ...
'Tag','StaticText2');
h1 = uicontrol('Parent',hf, ...
'Units','points', ...
'BackgroundColor',[0.8 0.8 0.8], ...
'ListboxTop',0, ...
'Position',[ 20.25 43.75 100.5 19.5 ], ...
'String',['T2 = ',num2str(T2)], ...
'Style','text', ...
'Tag','StaticText2');
num=[(max(ys)-ys(1))/us(long)];
den=[T1*T2 T1+T2 1];
sal=us(1)*step(num,den,t);
axes('Position',[ 0.53 0.35 0.4 0.57 ])
plot(t,ys,'b',t,sal,'r');
grid;
axis([0 max(t) 0 max(sal)+0.1*max(sal)]);
title('Respuestas del Sistema y el Modelo')
legend('Resp. del sistema', 'Resp. del modelo',4);
%*******************************************
98
h1 = uicontrol('Parent',hf, ...
'Units','points', ...
'BackgroundColor',[0.8 0.8 0.8], ...
'ListboxTop',0, ...
'Position',[271.5 70.25 120 15], ...
'String','Función de Transferencia', ...
'Style','text', ...
'Tag','StaticText7');
h1 = uicontrol('Parent',hf, ...
'Units','points', ...
'BackgroundColor',[0.8 0.8 0.8], ...
'ListboxTop',0, ...
'Position',[306 50 45 15], ...
'String',poly2str(num,'s'), ...
'Style','text', ...
'Tag','StaticText6');
h1 = uicontrol('Parent',hf, ...
'Units','points', ...
'BackgroundColor',[0.8 0.8 0.8], ...
'ListboxTop',0, ...
'Position',[ 267.75 38 132 15 ], ...
'String','_____________________________', ...
'Style','text', ...
'Tag','StaticText9');
h1 = uicontrol('Parent',hf, ...
'Units','points', ...
'BackgroundColor',[0.8 0.8 0.8], ...
'ListboxTop',0, ...
'Position',[275.25 15.5 114.75 15], ...
'String',poly2str(den,'s'), ...
'Style','text', ...
'Tag','StaticText8');
%*******************************************
end